
title: Lucas's Test Prot
title_caption: Status, in progress eternally
email: zapicolucas@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
favicon: /assets/img/favicon32.png  #16x16 or 32x32
profile_image: /assets/img/main-profile.jpg




# Build settings
markdown: kramdown


# LOCAL DEVELOPMENT
host: 127.0.0.1
port: 4466
exclude:
  - .gitignore
