
title: Lucas Zapico's online identity
title_caption: Status, in progress eternally
email: zapicolucas@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
favicon: /assets/img/mark/favicon/mark-v1.1.4-favicon-32@1x.png  #16x16 or 32x32
profile_image: /assets/img/main-profile.jpg


# BUILD SETTING
markdown: kramdown
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

# LOCAL DEVELOPMENT
host: 127.0.0.1
port: 4466
exclude:
  - .gitignore
  - /public-assets
  - Gemfile
  - Gemfile.lock
  - node_modules
  - /bundle/
  - /cache/
  - /gems/
  - /ruby/
  - /pages/projects/wip/
  - /pages/test
  - /pages/all-projects
  - /assets/img/sitemap-img

# OPTIMIZATION
sass:
 style: compressed

# # PLUGINS
plugins:
  # - jekyll-assets
  # - jekyll-sitemap


# OTHER MEDIA OUTLETS
twitter_username: https://twitter.com/lucas_zapico_10
github_username:  LucasZapico
github_link: https://github.com/LucasZapico
facebook_link: https://www.facebook.com/lucas.zapico.7
linkedin_link: https://www.linkedin.com/in/lucasmmzapico/
pinterest_link:
codepen_link: https://codepen.io/LucasZapico
instagram_link: https://www.instagram.com/10zapico/
